# Generated by Django 5.2.3 on 2025-07-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('username', models.CharField(default='', max_length=20)),
                ('upass', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
