# Generated by Django 5.2.3 on 2025-07-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('author', models.CharField(default='', max_length=20)),
                ('docs', models.FileField(default='', max_length=20, upload_to='book/docs')),
                ('cover', models.ImageField(default='', max_length=20, upload_to='book/cover')),
            ],
        ),
    ]
