# Generated by Django 5.2.3 on 2025-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='stud',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
