# Generated by Django 5.2.3 on 2025-07-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stud_gender_alter_stud_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='lang',
            field=models.CharField(default='', max_length=50),
        ),
    ]
