# Generated by Django 5.2.3 on 2025-07-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_stud_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='status',
            field=models.CharField(default='BLOCK', max_length=20),
        ),
    ]
